### ISSUE TITLE
Fatal error: Method Zend\View\Helper\HeadTitle::__toString() must not throw an exception

### ISSUE THREAD

**Issue by anil7-rvce** [olegkrivtsov/using-zf3-book-samples#10]
Fatal error: Method Zend\View\Helper\HeadTitle::__toString() must not throw an exception in C:\xampp\htdocs\formdemo\module\Application\view\layout\layout.phtml on line 0

I am getting the above error for zend framework 3 for all the four modules you have provided, ans will be appreciated.

**Comment by no1done** [comment]
Try installing the php-intl extension.

**Comment by olegkrivtsov** [comment]
Try this: `sudo apt-get install php-gd php-intl`
