### ISSUE TITLE
Syntax error in css file line 73 in userdemo/public/css/styles.css.

### ISSUE THREAD

**Issue by dawid83** [olegkrivtsov/using-zf3-book-samples#12]
##31811D instead of #31811D.

**Comment by olegkrivtsov** [comment]
There are only 59 lines in https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/userdemo/public/css/style.css Not sure where this error is located.

**Comment by dawid83** [comment]
I'm sorry that's for ocramius in ocramius/proxy-manager/html-docs/css/styles.css. I don't know why the library proxy-manager contains this file and index file. I download library using composer in your project.

**Comment by olegkrivtsov** [comment]
Closing then.
