### ISSUE TITLE
using-zf3-book-samples/formdemo/module/Application/src/Service/

### ISSUE THREAD

**Issue by ghost** [olegkrivtsov/using-zf3-book-samples#15]
When I try to call MailSernderservice it gives error in " syntax error, unexpected '(' in C:\xampp\htdocs\CarRepair\vendor\jenzri-nizar\zf3-bootstrapdatepicker\src\Form\View\Helper\Datepicker.php on line 112"

please help me what i need to change

**Comment by SilverioMiranda** [comment]
Your error is related to third-party module called "jenzri-nizar\zf3-bootstrapdatepicker"
You need to post this issue at https://github.com/jenzri-nizar/zf3-bootstrapdatepicker

**Comment by olegkrivtsov** [comment]
Closing.
