### ISSUE TITLE
UserDemo - database credentials are not passed correctly

### ISSUE THREAD

**Issue by vineethmathews** [olegkrivtsov/using-zf3-book-samples#17]
My Local.php for userdemo looks as below

....
`'params' => [
                    'host'     => '127.0.0.1',
                    'user'     => 'userdemo',
                    'password' => 'password',
                    'dbname'   => 'userdemo',
                ]`
I have created the user called userdemo identified by password. The database is created. When I click on SignIn, the following error occurs

`An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user 'username'@'localhost' to database 'database'`

I have made it work only by editing the connect function in driver.php of PDOMysql and setting  the $params values with the `right username and password as shown below

class Driver extends AbstractMySQLDriver
{
    /**
     * {@inheritdoc}
     */
    public function connect(array $params, $username = null, $password = null, array $driverOptions = array())
    {
        

 `$params['dbname']='userdemo';
        $params['user']='userdemo';
        $username='userdemo';`       
        try {

Is this a bug or is it because i have to do something. I feel it is more of the later because, when I run 
doctrine-module migrations:status, the databasename is shown as 'database' which is the same name occuring for database in the error itself

**Comment by SilverioMiranda** [comment]
Your local.php must be like this :

```
return [
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'driverClass' => \Doctrine\DBAL\Driver\PDOMySql\Driver::class,
                'params' => [
                    'host' => 'localhost',
                    'port' => '3306',
                    'user' => 'root',
                    'password' => 'password',
                    'dbname' => 'database_name_book'
                ]
            ]
        ]
    ]
]
```

**Comment by olegkrivtsov** [comment]
Your `local.php` seems to contain wrong database connection parameters.
