### ISSUE TITLE
Найдена ошибка в приложении RoleDemo

### ISSUE THREAD

**Issue by drakulitka** [olegkrivtsov/using-zf3-book-samples#20]
Значение переменной [`$role`](https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/roledemo/module/User/src/Controller/RoleController.php#L141)
в дальнейшем перезаписывается в цикле [`foreach`](https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/roledemo/module/User/src/Controller/RoleController.php#L155)
В результате [вот тут](https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/roledemo/module/User/src/Controller/RoleController.php#L192) значение переменной $role будет равно последнему извлеченному элементу массива в вышеуказанном цикле foreach, а не извлеченному из базы данных, как предполагалось.

При редактировании роли, в поле 'name' формы, можно увидеть название постоянно одной и той же роли.

Как вариант, можно переименовать переменную в цикле `foreach`:
```
foreach ($roles as $roleItem) {
    $roleList[$roleItem->getId()] = $roleItem->getName();
}
```
Это просто пример.

**Comment by olegkrivtsov** [comment]
Исправил, спасибо.
