### ISSUE TITLE
Undefined variable $result

### ISSUE THREAD

**Issue by drakulitka** [olegkrivtsov/using-zf3-book-samples#21]
Undefined variable [$result](https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/roledemo/module/User/src/Service/RbacManager.php#L72)

```
// Try to load Rbac container from cache.
$this->rbac = $this->cache->getItem('rbac_container', $result);
if (!$result) {
...
```

**Comment by olegkrivtsov** [comment]
Fixed, thanks.
