### ISSUE TITLE
CurrentUser view helper returns array instead of entity object

### ISSUE THREAD

**Issue by ezkimo** [olegkrivtsov/using-zf3-book-samples#29]
The user role demo contains a current user view helper, which should return an user entity object, if a user was found by an email address. Instead of the user entity an array is returned. This is a bit confusing because this breaks method chaining in the view. 

Actually the problem is in line 54 of /User/src/View/Helper/CurrentUser.php

    $this->user = $this->entityManager->getRepository(User::class)->find(array(
        'email' => $this->authService->getIdentity()
    ));

This should be changed into

    $this->user = $this->entityManager-getRepository(User::class)->findOneBy([
        'email' => $this->authService->getIdentity()
    ]);

This change leads to method chaining in the view like the following example.

    <p><?= $this->currentUser()->getFullName() ?></p>

**Comment by olegkrivtsov** [comment]
Fixed, thanks!
