### ISSUE TITLE
 database migrations error

### ISSUE THREAD

**Issue by adjaya-dev** [olegkrivtsov/using-zf3-book-samples#30]
running database migrations provide an exception:

  [Doctrine\DBAL\Exception\TableExistsException]                               
  An exception occurred while executing 'CREATE INDEX post_id_index ON post_t  
  ag (post_id)':                                                               
  SQLSTATE[HY000]: General error: 1 index post_id_index already exists         
   
  [Doctrine\DBAL\Driver\PDOException]                                   
  SQLSTATE[HY000]: General error: 1 index post_id_index already exists  
  
  [PDOException]                                                        
  SQLSTATE[HY000]: General error: 1 index post_id_index already exists

**Comment by olegkrivtsov** [comment]
Strange error. Do you run migrations on an empty database?

**Comment by adjaya-dev** [comment]
I'm trying this on a sqlite database.
I first just configure the parameters in config/autoload/local.php like this:

`use Doctrine\DBAL\Driver\PDOSqlite\Driver as PDOSqliteDriver;
return [
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'driverClass' => PDOSqliteDriver::class,
                'params' => [
			'path' => 'data/blog.sqlite',
                ]
            ]
        ]
    ]
];`

Then I run the command
./vendor/bin/doctrine-module migrations:migrate

The database is well created at this time, but I get the error, so the migration is not complete.
The tables are created but not the indexes.

**Comment by olegkrivtsov** [comment]
Hmm. I never tested it with sqlite, so can't advice. I think something is wrong with the way indexes are created in sqlite. Does the sample work with MySQL?

**Comment by adjaya-dev** [comment]
Yes, the sample works with mysql.
I'll do some more tests to try to see what is wrong with sqlite, and give you a feedback here.

**Comment by adjaya-dev** [comment]
With sqlite, i solve the indexes problem like this :
[https://github.com/adjaya-dev/using-zf3-book-samples/commit/f028b20210edd4ef3af71f63c156504a0350b8b7](https://github.com/adjaya-dev/using-zf3-book-samples/commit/f028b20210edd4ef3af71f63c156504a0350b8b7)

**Comment by olegkrivtsov** [comment]
Thanks, @adjaya-dev. I used your code. Fixed.
