### ISSUE TITLE
doctrine orm:validate-schema # Error: " The table with name 'role.demo.role_hierarchy' already exists."

### ISSUE THREAD

**Issue by C0DE8** [olegkrivtsov/using-zf3-book-samples#31]
Hello,

I have "cloned" your sample and installed (successfully) the "role demo".

But if I execute the following command on the console (cli):

`# doctrine orm:validate-schema `

I add the "cli-config.php" file to get doctrine console to work.
```
<?php
//Insert in config folder as file name cli-config.php

// bootstrap.php
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Tools\Console\ConsoleRunner;

require "vendor/autoload.php";

// Create a simple "default" Doctrine ORM configuration for Annotations
$paths = [__DIR__.'/../module/User/src/Entity'];
$isDevMode = true;

$config = Setup::createAnnotationMetadataConfiguration($paths, $isDevMode, null, null, false);

// database configuration parameters
$conn = array(
    'driver'    => 'pdo_mysql',
    'host'      => 'localhost',
    'port'      => '3306',
    'user'      => '*****',
    'password'  => *****',
    'dbname'    => '*****',
    'charset'   => 'utf8',
    'driverOptions' => [
        PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8'
    ]
);
```

$entityManager = EntityManager::create($conn, $config);

return ConsoleRunner::createHelperSet($entityManager);

I get the following error:
"**The table with name 'oleg_rbac.role_hierarchy' already exists.**"

![oleg_rbac__role-demo__doctrine_2__validate-schema__error__table_exists](https://user-images.githubusercontent.com/20956699/35959755-3a992d34-0ca7-11e8-970b-014b701b7e3a.png)
_(I use another database name than oleg)_

So,t he application in general works (login, edit user, new user, edit/new roles, ...), but if I add other entities and want to use "doctrine orm:validate-schema" it is **not** possible.

I investigate a bit and I think in the "Role" Entity is the problem:

```
//...
    /**
     * @ORM\ManyToMany(targetEntity="User\Entity\Role")
     * @ORM\JoinTable(name="role_hierarchy",
     *      joinColumns={@ORM\JoinColumn(name="child_role_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="parent_role_id", referencedColumnName="id")}
     *      )
     */
    private $parentRoles;

    /**
     * @ORM\ManyToMany(targetEntity="User\Entity\Role")
     * @ORM\JoinTable(name="role_hierarchy",
     *      joinColumns={@ORM\JoinColumn(name="parent_role_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="child_role_id", referencedColumnName="id")}
     *      )
     */
    protected $childRoles;
//...
```
I could delete one of the relation above, but this will also break the erm of the rbac. One of the possibilities (child or parent role) will not work after that.

So., for now I did not found any solution.

My goal is to use the RBAC from Oleg, but also use doctrine on the consle ("doctrine orm-validate-schema", "doctrine orm:schema-tool:pdate", ...).

Could anyone help please?

**Comment by olegkrivtsov** [comment]
Take a look at #19. Does this help?

**Comment by C0DE8** [comment]
@olegkrivtsov 
Thanks for the hint, I did not see this older issue.

If I drop the database, do the changes from #19 in the Role.php and in the migrations, execute then the migrations, call the "orm:validate-schema" I get another error (errors):

with additional "mappedBy" and "inversedBy":
![oleg_rbac__role-demo__doctrine_2__validate-schema__error__table_exists_2](https://user-images.githubusercontent.com/20956699/35963293-96f1ea64-0cb4-11e8-9b17-c5e17d2ec39c.png)

without "mappedBy" and "inversedBy"
![oleg_rbac__role-demo__doctrine_2__validate-schema__error__table_exists_3](https://user-images.githubusercontent.com/20956699/35963519-43434858-0cb5-11e8-9bf1-54c88eedc136.png)

I'am using the folwoing version:
```
doctrine/orm                             2.6.0
doctrine/doctrine-module                 1.2.0
doctrine/doctrine-orm-module             1.1.5
```

What am I doing wrong?

**Comment by C0DE8** [comment]
After investigating some time, I found out, that the SQL which is created by the "doctrine migration" is another SQL than doctrine create with nativ usage of "doctrine orm:schema-tool:create" command. I extend the user with a UserStatus entity (to get riod off the status constants. Moreover I compare quite often the created SQL of doctrine and the migrations.

For now I can safely use "doctrine orm:schema-tool:create" to create the DB. Next step is to change the doctrine migration that it produces the same (or nearly the same) SQL, so that doctrine will accept the database if checked with "doctrine orm:validate-schema".

![oleg_rbac__role-demo__doctrine_2__validate-schema__success_with_native_doctrine_creation](https://user-images.githubusercontent.com/20956699/35980930-45e16090-0cec-11e8-9683-97e7f3ba5056.png)

**Comment by C0DE8** [comment]
Next level successfully reached!

Using command 
"**doctrine orm:schema-tool:create**" 
and 
migration execution 
"**./vendor/bin/doctrine-module migrations:migrate**" 
create now the same (SQL) database and doctrine (with command "**doctrine orm:validate-schema**") is happy again. ;-)

![oleg_rbac__role-demo__doctrine_2__validate-schema__success_with_native_doctrine_creation__and__doctrine-migration](https://user-images.githubusercontent.com/20956699/35984747-59cab4fe-0cf5-11e8-9c73-fdc29df73ffb.png)

**Next Stage:**
Check and correct the application PHP code ("role demo") to work successfully again.

**Comment by C0DE8** [comment]
I found out, that the "role hirarchy" is neither the display nor the save are implemented. So I implemented and tested both. Now you can set one or more roles where permissions are inherited from.

**Set inherited role(s):**
![oleg_rbac__role-demo__implement_the_role_hierarchy_view_edit_save_with_permissions_inherit_view_1](https://user-images.githubusercontent.com/20956699/36027968-9cc239b4-0d9d-11e8-98ae-b15477d994ae.png)


**Show and edit permissions (with disabled inherited permissions):**
![oleg_rbac__role-demo__implement_the_role_hierarchy_view_edit_save_with_permissions_inherit_view_2](https://user-images.githubusercontent.com/20956699/36027906-71e4ede0-0d9d-11e8-9ea6-b680b92f8316.png)

**Next (and final) Stage:**
Fork your Sample repo on github, commit my changes and create a pull request; maybe you (@olegkrivtsov) find it usefull an integrate my changes.

But I have raised code to PHP 7.1 (incl. return type hints, ...) :-)

**Comment by drakulitka** [comment]
**C0DE8**, please show an example of Your code

**Comment by C0DE8** [comment]
@drakulitka Yes, of course. I will optimize and cleanup my code, after that I clone the original repository and update it with my code.

**Comment by Mecanik** [comment]
This issue should not be closed, because the errors are there. The problems should be fixed and comitted to master branch. 

Any other people that want's to use this example will get very confused following the issues and trying to fix it...

**Comment by olegkrivtsov** [comment]
Hi @C0DE8 I've done some improvements in ORM mapping in https://github.com/olegkrivtsov/using-zf3-book-samples/commit/3f25fe7f5e1ef213c7e262f71506e89ecf8c1510. Can you check if this helps?

**Comment by olegkrivtsov** [comment]
Closing - should be fixed now.

**Comment by abu3alae** [comment]
thanks for your help,
---------------------------------------------------------------------
Mapping
-------                                                                                                                        
 [OK] The mapping files are correct.                                                                                                                                                                                                         
Database
--------                                                                                                                   
 [OK] The database schema is in sync with the mapping files.      
--------------------------------------------------------------------

but I still have an migrations problem.

 ./vendor/bin/doctrine-migrations status
PHP Fatal error:  Uncaught Doctrine\Migrations\Configuration\Migration\Exception\MissingConfigurationFile: It was not possible to locate any configuration file. in /home/xxx/www/webapp/vendor/doctrine/migrations/lib/Doctrine/Migrations/Configuration/Migration/Exception/MissingConfigurationFile.php:14
Stack trace:
#0 /home/xxx/www/webapp/vendor/doctrine/migrations/lib/Doctrine/Migrations/Configuration/Migration/ConfigurationFileWithFallback.php(52): Doctrine\Migrations\Configuration\Migration\Exception\MissingConfigurationFile::new()
#1 /home/xxx/www/webapp/vendor/doctrine/migrations/lib/Doctrine/Migrations/DependencyFactory.php(158): Doctrine\Migrations\Configuration\Migration\ConfigurationFileWithFallback->getConfiguration()
#2 /home/xxxwww/webappvendor/doctrine/migrations/lib/Doctrine/Migrations/DependencyFactory.php(184): Doctrine\Migrations\DependencyFactory->getConfiguration()
#3 /home/xxx/www/webapp/vendor/doctrine/migrations/lib/Doctrine/Migrations/DependencyFacto in /home/xxx/www/webapp/vendor/doctrine/migrations/lib/Doctrine/Migrations/Configuration/Migration/Exception/MissingConfigurationFile.php on line 14
