### ISSUE TITLE
Issue in RbacManager when we use dynamic assertion

### ISSUE THREAD

**Issue by 0kph** [olegkrivtsov/using-zf3-book-samples#32]
If I'm not wrong, in RbacManager You have issue. Let's assume:
user has assigned role1, role2
role1 has assign permision1 but NOT pass dynamic assertion
role2 has assign permision1 and pass dynamic assertion

Line 148 makes, we will not have chance to check role2, because method return false after role1 and breaks foreach loop.

https://github.com/olegkrivtsov/using-zf3-book-samples/blob/7f89185cd231e6a5f7ec98ee56aacdd74852e344/roledemo/module/User/src/Service/RbacManager.php#L137-L150

**Comment by olegkrivtsov** [comment]
Hmm.. seems like a bug.

**Comment by olegkrivtsov** [comment]
Should be fixed in https://github.com/olegkrivtsov/using-zf3-book-samples/commit/a86e47713731077679e914e8fa74999825b3e718 

Does this work for you?

**Comment by 0kph** [comment]
That is how I resolved this problem in my system. So should be fine. 
Similar problem is in AuthManager.php where is loop  "foreach ($items as $item)" if You will have more than 1 item, but first fail, method brak loop and other $ilem are ignored. But I need to spend some time to deep analize :)

Btw, great THE JOB  ;)
