### ISSUE TITLE
Redirect Url in AuthController

### ISSUE THREAD

**Issue by drakulitka** [olegkrivtsov/using-zf3-book-samples#33]
Подскажите, передача переменной в AuthController'е методе loginAction() `$redirectUrl` в шаблон не обязательна?
Она там нигде не используется.

`return new ViewModel([`
    `'form' => $form,`
    `'isLoginError' => $isLoginError,`
    `'redirectUrl' => $redirectUrl`
`]);`

**Comment by olegkrivtsov** [comment]
Хм.. видимо нет, она действительно не используется. Спасибо.
