### ISSUE TITLE
There is no method - setParentRole()

### ISSUE THREAD

**Issue by drakulitka** [olegkrivtsov/using-zf3-book-samples#34]
It seems this method is missing in the Role entity?
[setParentRole($parentRole)](https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/roledemo/module/User/src/Service/RoleManager.php#L139)

**Comment by olegkrivtsov** [comment]
Hmm.. strange. Do you have an error message?

**Comment by drakulitka** [comment]
There are no error messages, because I haven't written tests yet, I just wanted to see how this method is implemented, and I haven't found it, maybe I'm wrong.
