### ISSUE TITLE
Role Inheritance

### ISSUE THREAD

**Issue by sheridans** [olegkrivtsov/using-zf3-book-samples#35]
roledemo.

Role inheritance does not work.

To reproduce:
Create a new role "Test Role" for example, and choose to inherit roles from Administrator.
Create a new user, assign the "Test Role" to to user

Result: Newly created user cannot access any admin functions as role is not inherited.
role_hierarchy table is not populated with data.

You would expect something similar to the code specified below to happen.
` insert into role_hierarchy (parent_role_id,child_role_id) VALUES (1,3);`

When manually inserting the code (cmd as above), the role are still not applied on login.

Seems to be similar to issue #31

**Comment by drakulitka** [comment]
Relationship tables allow for this functionality, but the application logic (code) this functionality is missing!!! You need to add by this logic!

**Comment by sheridans** [comment]
I proposed a PR which adds this logic into the code.

**Comment by olegkrivtsov** [comment]
Fixed
