### ISSUE TITLE
User Demo: Hash the password reset token when storing in DB

### ISSUE THREAD

**Issue by olegkrivtsov** [olegkrivtsov/using-zf3-book-samples#39]
As reported by Greg via Disqus: https://olegkrivtsov.github.io/using-zend-framework-3-book/html/en/User_Management__Authentication_and_Access_Filtering/Adding_UserManager_Service.html#comment-3907675687

> I've seen it recommended to hash the token before storing it in the db. That way, if the db contents leak out somehow, someone can't use whatever tokens are there to reset passwords.

**Comment by rubensilva20** [comment]
I am currently working on a project where I implemented this funcionality where I store the token using bcrypt. Do you want me to make a pull request if it's of your interest? 

Cheers.

**Comment by olegkrivtsov** [comment]
Hi @deutschland2k that would be great!

**Comment by olegkrivtsov** [comment]
This should work now. Closing.
