### ISSUE TITLE
AuthController not found

### ISSUE THREAD

**Issue by ynachti** [olegkrivtsov/using-zf3-book-samples#4]
I get this error I am not sure why could you please give some hint

    Unable to resolve service "User\Controller\AuthController" to a factory; are you certain you provided it during configuration?

**Comment by olegkrivtsov** [comment]
Do you experience this problem in unchanged User Demo sample, or did you make some changes to it?

**Comment by ynachti** [comment]
It is unchanged however I copied the 'User' directory into my own application. I discovered that composer.json was actually in the root of userdemo so the vendor did not get updated with the dependencies required. Also psr config was missing the User line
 "autoload": {
        "psr-4": {
            "Application\": "module/Application/src/",
      --->       "User\": "module/User/src/"
        }
    },
which explains why the controllers were not found. 
in the end I had to add the session_key config into my global.php
and problem solved. 
now I am working on migrating the db. I am working with Oracle so hopefully won't have issues there.
Hope this helps.
