### ISSUE TITLE
Vendor file missing  

### ISSUE THREAD

**Issue by madhavyagnik** [olegkrivtsov/using-zf3-book-samples#41]
Vendor file is missing

**Comment by olegkrivtsov** [comment]
Not sure what you mean. What is the vendor file?

**Comment by rubensilva20** [comment]
He's basically saying there's no vendor folder. For that you should go to CMD, go to your project root through there and type: **composer install**. Which will follow composer.json and install all the stuff needed which is not 100% certain that will not give you errors but give it a try.

**Comment by olegkrivtsov** [comment]
Closing since this seems to be not an issue with the code.
