### ISSUE TITLE
new'ing the InputFilter in a form will bite you eventually

### ISSUE THREAD

**Issue by bitwombat** [olegkrivtsov/using-zf3-book-samples#42]
Hi Oleg,

I just spent 3+ hours tracing down why my custom validator was always being created with the InvokableFactory, rather than the ReflectionBasedAbstractFactory that I was assigning in my 'validators' config key.

The reason for me was a mistake you're making here:
https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/formdemo/module/Application/src/Form/ContactForm.php#L165

If you new the InputFilter, it doesn't have any config.  And, the ValidatorPluginManager that gets plugged into it will just be the default one, not one with your ServiceManager configs.

Instead, you should `$inputFilter = $this->getInputFilter()`  This does a very important extra step after the new:

(from Zend\Form\Form)

        if (! isset($this->filter)) {
            $this->filter = new InputFilter();
            $this->filter->setFactory($this->getFormFactory()->getInputFilterFactory());
        }

The Form already has a FormFactory set on it, which has a InputFilterFactory, and these have the config injected into them, so your ValidatorPluginManager will have it too, meaning your 'validators' config key will be used.

That's probably not all as clear as it could be because a) it's complicated and b) I just figured that out 10 minutes ago so it's probably not clear enough in my own head yet.

**Comment by olegkrivtsov** [comment]
Hi @bitwombat good finding! Looks like a bug.

**Comment by olegkrivtsov** [comment]
@bitwombat I've tried to use `$this->getInputFilter()` in all forms in samples.
