### ISSUE TITLE
Create forms with a factory?

### ISSUE THREAD

**Issue by olegkrivtsov** [olegkrivtsov/using-zf3-book-samples#43]
As reported by Greg via Disqus: https://olegkrivtsov.github.io/using-zend-framework-3-book/html/en/Checking_Input_Data_with_Validators/Writing_Own_Validator.html#comment-3923385232

> Hi Oleg - how are you able to avoid using the FormElementManager, factories, and the init function in your forms? If I recall from the docs, things might not be initialised if you don't create Forms via the FormElementManager...

> Also when your custom validator needs a factory other than InvokableFactory... I speak from first-hand experience having taken lots of hours to figure out what was going on. Two ValidatorChains were being created because I was new'ing my InputFilter.

> I take it from the ZF folks that their philosophy is that your application should be "factories all the way down" meaning only new'ing model and value objects - everything else is supposed to be gotten via factories. When I've ignored this in Forms, I've gotten bitten (twice now).

> Your code works (obviously), but following your example will lead others to make the same mistakes I've made.

**Comment by olegkrivtsov** [comment]
@bitwombat, I've re-read this doc: https://docs.zendframework.com/zend-form/quick-start/ and I was unable to see the recommendation to create form via `FormElementManager`. Can you provide some resource where such usage is described?

**Comment by olegkrivtsov** [comment]
@bitwombat, after some thinking I've decided to close this - the book is for beginners, the thing you suggest is mostly for advanced users (custom elements, custom validators, etc). They can still read the docs if really required.

**Comment by bitwombat** [comment]
@olegkrivtsov Your call, of course, but you are creating a custom validator here, so your book does have a few advanced techniques at least.

I've lost hours several times by not following the best practice of 'always using factories'... learned mostly from chat and [this section of the manual](https://docs.zendframework.com/zend-form/advanced/#creating-custom-elements).
