### ISSUE TITLE
User Demo - Can't log in - Form validation fails

### ISSUE THREAD

**Issue by olegkrivtsov** [olegkrivtsov/using-zf3-book-samples#47]
As reported by Nicolas via Disqus: https://olegkrivtsov.github.io/using-zend-framework-3-book/html/en/User_Management__Authentication_and_Access_Filtering/Get_User_Demo_Sample_from_GitHub.html#comment-3924785774

> In the userdemo I can't seem to login. When I enter the credentials it keeps saying the credentials are invalid. I can see the user is created on first login in the database... 
I am debugging the

loginAction 
but no luck so far. 
Any idea why this is happening?

EDIT: After further debugging I found the

$form->isValid()
rever returns true.. But I can't seem to figure out why.

**Comment by jan-secalith** [comment]
It works fine for me.
![zf3_book_issue_47](https://user-images.githubusercontent.com/39198110/41047418-75eee310-69a4-11e8-9574-122f8435dabb.png)

**Comment by olegkrivtsov** [comment]
Hmm.. I can't reproduce this with both userdemo and roledemo.

**Comment by olegkrivtsov** [comment]
Can't reproduce - no response from the reporter - closing.
