### ISSUE TITLE
I can not "composer install" project (php 7.2 win)

### ISSUE THREAD

**Issue by glk2** [olegkrivtsov/using-zf3-book-samples#48]
I can not "composer install" project (php 7.2)
Problem 1
 - The requested PHP extension ext-mcrypt * is missing from your system. Inst
all or enable PHP's mcrypt extension.
MCrypt was removed from PHP7.2.
https://stackoverflow.com/questions/49323908/php-7-2-with-mcrypt-in-windows
Can you help ?

**Comment by olegkrivtsov** [comment]
Hi @glk2 as a temporary workaround you can remove the `ext-mcrypt` line from requirements in `composer.json`.

**Comment by olegkrivtsov** [comment]
This should be fixed now. @glk2 can you test with PHP 7.2?

**Comment by glk2** [comment]
Thank you! Problem solved.
