### ISSUE TITLE
Method Zend\View\Helper\HeadTitle::__toString() must not throw an exception

### ISSUE THREAD

**Issue by wdesign22** [olegkrivtsov/using-zf3-book-samples#5]
Добрый день. Тут можно по русски писать?
В общем развернул из архива helloworld в отдельную папку . 

Выдает ошибку:
Fatal error: Method Zend\View\Helper\HeadTitle::__toString() must not throw an exception, caught Zend\I18n\Exception\ExtensionNotLoadedException: Zend\I18n\Translator component requires the intl PHP extension in /var/www/helloworld/module/Application/view/layout/layout.phtml on line 0

композером все сгружал, 
конфиг хоста:

<VirtualHost *:80>
	ServerAlias www.helloworld  helloworld
	DocumentRoot /var/www/helloworld/public
	ServerName helloworld
  		<Directory /var/www/helloworld/>
    		DirectoryIndex index.php
        	AllowOverride All
        	Require all granted
  		</Directory>
	
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>

**Comment by olegkrivtsov** [comment]
Вам нужно установить расширения `gd` и `intl`:

`sudo apt-get install php-gd php-intl`

**Comment by wdesign22** [comment]
Заработало, спасибо!

**Comment by 0kph** [comment]
If you cant install ext/intl, you create a DummyTranslator. Just add to config:

```
 'translator' => [
       'locale' => 'en_EN',
 ]
```

> a DummyTranslator, for use when ext/intl is unavailable, or configuration dictates that translations are disabled.
