### ISSUE TITLE
Role Demo Sample- Role Hierarchy Problem

### ISSUE THREAD

**Issue by erkinaka** [olegkrivtsov/using-zf3-book-samples#52]
Hi,
i tried to use your role demo sample but i had a problem. when i try to add new role, demo doesn't save  the new role's parent roles to role_hierarchy db table, it added role but not parents. also update process has the same problem too.
i tried to solve this problem by changing  User\Entity\Role.php file at line 37 and line 46, like below. and it works but i don't it is proper because i don't know to use Doctrine. 

namespace User\Entity\Role.php

old 

>  /**
>      * @ORM\ManyToMany(targetEntity="User\Entity\Role", mappedBy="childRoles")  //line 37
>      * @ORM\JoinTable(name="role_hierarchy",
>      *      joinColumns={@ORM\JoinColumn(name="child_role_id", referencedColumnName="id")},
>      *      inverseJoinColumns={@ORM\JoinColumn(name="parent_role_id", referencedColumnName="id")}
>      *      )
>      */
>     private $parentRoles;
>     
>     /**
>      * @ORM\ManyToMany(targetEntity="User\Entity\Role", inversedBy="parentRoles") // line 46
>      * @ORM\JoinTable(name="role_hierarchy",
>      *      joinColumns={@ORM\JoinColumn(name="parent_role_id", referencedColumnName="id")},
>      *      inverseJoinColumns={@ORM\JoinColumn(name="child_role_id", referencedColumnName="id")}
>      *      )
>      */
>     protected $childRoles;

and the new

>  /**
>      * @ORM\ManyToMany(targetEntity="User\Entity\Role", inversedBy="parentRoles")   //line 37
>      * @ORM\JoinTable(name="role_hierarchy",
>      *      joinColumns={@ORM\JoinColumn(name="child_role_id", referencedColumnName="id")},
>      *      inverseJoinColumns={@ORM\JoinColumn(name="parent_role_id", referencedColumnName="id")}
>      *      )
>      */
>     private $parentRoles;
>     
>     /**
>      * @ORM\ManyToMany(targetEntity="User\Entity\Role", mappedBy="childRoles")   //line 46
>      * @ORM\JoinTable(name="role_hierarchy",
>      *      joinColumns={@ORM\JoinColumn(name="parent_role_id", referencedColumnName="id")},
>      *      inverseJoinColumns={@ORM\JoinColumn(name="child_role_id", referencedColumnName="id")}
>      *      )
>      */
>     protected $childRoles;

**Comment by olegkrivtsov** [comment]
This should work now.
