### ISSUE TITLE
Return value $false instead of false

### ISSUE THREAD

**Issue by 0kph** [olegkrivtsov/using-zf3-book-samples#7]
https://github.com/olegkrivtsov/using-zf3-book-samples/blob/master/userdemo/module/User/src/Validator/UserExistsValidator.php

Of course, uninitialized variable returns false, but nevertheless it is a mistake.

Btw, books & samples are better than official documentation... really.
```
    /**
     * Check if user exists.
     */
    public function isValid($value) 
    {
        if(!is_scalar($value)) {
            $this->error(self::NOT_SCALAR);
            return $false; <-------------------------------- here
        }
```

**Comment by olegkrivtsov** [comment]
Fixed. Thanks!
