### ISSUE TITLE
userdemo : doctrine-module migrations:migrate doesn't work

### ISSUE THREAD

**Issue by phil40** [olegkrivtsov/using-zf3-book-samples#9]
Hi Oleg,
I'm trying to install your "userdemo" but I have a problem.
Could you please tell me what is wrong?
I get this screen (cmd.exe of windows) :

> **## D:\xampp\php>php.exe ../htdocs/userdemo/vendor/bin/doctrine-module migrations:migrate**
> 
> dir=$(d=${0%[/\\]*}; cd "$d"; cd "../doctrine/doctrine-module/bin" && pwd)
> 
>###  # See if we are running in Cygwin by checking for cygpath program
> if command -v 'cygpath' >/dev/null 2>&1; then
>         # Cygwin paths start with /cygdrive/ which will break windows PHP,
>         # so we need to translate the dir path to windows format. However
>         # we could be using cygwin PHP which does not require this, so we
>         # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
>         if [[ $(which php) == /cygdrive/* ]]; then
>                 dir=$(cygpath -m "$dir");
>         fi
> fi
> 
> dir=$(echo $dir | sed 's/ /\ /g')
> "${dir}/doctrine-module" "$@"
> 
> **## D:\xampp\php>**

I don't know what this means and don't know what to do!
Thank you

**Comment by olegkrivtsov** [comment]
Not sure what this output means. I never tested User Demo under Windows/XAMPP. Did you try to install it in Linux?

**Comment by phil40** [comment]
No. But did you try to test it on windows?
Thank you for your time.

**Comment by olegkrivtsov** [comment]
No I didn't try it on Windows. I recommend to use Linux.
